# Site wide configuration

title:            Amir Razmjou
locale:           en_US
url:              
destination:      ../arazmj.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Amir Razmjou
  avatar: bio-photo.jpg
  bio: "Researcher"
  email: arazmjou2014@my.fit.edu
  disqus-shortname: amirrazmjousfitblog
  twitter: arazmj
  facebook: amir.razmjou
  google:
    plus: 113817162653877217251
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: arazmj
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: amirrazmjou
  instagram: arazmj
  lastfm: shotormotor
  tumblr: #username
  pinterest: amirrazmjou
  foursquare: user/88238703
  steam: #username
  dribbble: #username
  youtube: arazmj
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
